{"frames":[{"func":"train_and_predict_logistic_regression(train_data_new, test_data_new, \n    \"Satisfaction_dummy\", lambda)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"as.matrix(test_data[, setdiff(names(test_data), predictor_col)])","file":"","line_number":8,"end_line_number":8,"character_number":3,"end_character_number":76},{"func":".handleSimpleError(function (cond) \n.Internal(C_tryCatchHelper(addr, 1L, cond)), \"incorrect number of dimensions\", \n    base::quote(test_data[, setdiff(names(test_data), predictor_col)]))","file":"","line_number":8,"end_line_number":8,"character_number":3,"end_character_number":76},{"func":"h(simpleError(msg, call))","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0}],"message":"Error in h(simpleError(msg, call)) : \n  在为'as.matrix'函数选择方法时评估'x'参数出了错: incorrect number of dimensions \n"}